### ISSUE TITLE
Add functionality to schedule update checking for core, plugins and themes

### ISSUE THREAD

**Issue by tersmitten** [Oefenweb/ansible-wordpress#11]
See:

**Core**
* http://wp-cli.org/commands/core/check-update/
* http://wp-cli.org/commands/core/update/

**Plugins**
* http://wp-cli.org/commands/plugin/update/ (`--dry-run`)

**Themes**
* http://wp-cli.org/commands/theme/update/ (`--dry-run`)

**Comment by mvdriel** [comment]
How about an existing WordPress control panel? Something like InfiniteWP: http://infinitewp.com/

**Comment by tersmitten** [comment]
@Yennick Let's do that
