### ISSUE TITLE
Add support to set autoload for options

### ISSUE THREAD

**Issue by tersmitten** [Oefenweb/ansible-wordpress#33]

**Comment by mvdriel** [comment]
This is not supported by wp-cli: http://wp-cli.org/commands/option/

@tersmitten How do you want to realize this? By using wp-cli query?

**Comment by tersmitten** [comment]
@mvdriel Yes it is: http://wp-cli.org/commands/option/add/ :-)

**Comment by mvdriel** [comment]
@tersmitten It seems partly supported. Not on update http://wp-cli.org/commands/option/update/ I will implement this parameter for add tomorrow

**Comment by tersmitten** [comment]
https://github.com/wp-cli/wp-cli/issues/2081

**Comment by tersmitten** [comment]
Fixed in #35
